name: solution_ps2_ex3_database
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - polars
  - duckdb
  - click
  - ipykernel
  - jupyter
  - pre-commit
  - black
  - isort
  - ruff
  - sqlite
  - pip
  - pip:
      - kaggle
